#!/bin/tcsh

#Written by Douglas H. Schultz

#Organize stats

setenv studir '/projects/Saidi'
setenv expdir '/projects/Saidi/rawdata'
setenv subdir ${expdir}
setenv resdir '/projects/Saidi/rawdata/Results'

cd ${resdir}/MVM

3dClusterize -inset MVM_stroop+tlrc -ithr 1 -idat 1 -NN 2 -1sided RIGHT_TAIL 12.609 -clust_nvox 7 -pref_map cond_ME_order -pref_dat cond_ME_clust_thresh > cond_ME.txt

3dROIstats \
-mask cond_ME_order+tlrc \
/projects/Saidi/rawdata/Results/SUB_01_ses-01_stroop/SUB_01_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_01_ses-01_stroop/SUB_01_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_01_ses-02_stroop/SUB_01_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_01_ses-02_stroop/SUB_01_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_02_ses-01_stroop/SUB_02_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_02_ses-01_stroop/SUB_02_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_02_ses-02_stroop/SUB_02_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_02_ses-02_stroop/SUB_02_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_03_ses-01_stroop/SUB_03_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_03_ses-01_stroop/SUB_03_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_03_ses-02_stroop/SUB_03_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_03_ses-02_stroop/SUB_03_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_04_ses-01_stroop/SUB_04_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_04_ses-01_stroop/SUB_04_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_04_ses-02_stroop/SUB_04_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_04_ses-02_stroop/SUB_04_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_05_ses-01_stroop/SUB_05_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_05_ses-01_stroop/SUB_05_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_05_ses-02_stroop/SUB_05_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_05_ses-02_stroop/SUB_05_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_06_ses-01_stroop/SUB_06_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_06_ses-01_stroop/SUB_06_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_06_ses-02_stroop/SUB_06_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_06_ses-02_stroop/SUB_06_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_07_ses-01_stroop/SUB_07_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_07_ses-01_stroop/SUB_07_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_07_ses-02_stroop/SUB_07_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_07_ses-02_stroop/SUB_07_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_08_ses-01_stroop/SUB_08_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_08_ses-01_stroop/SUB_08_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_08_ses-02_stroop/SUB_08_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_08_ses-02_stroop/SUB_08_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_09_ses-01_stroop/SUB_09_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_09_ses-01_stroop/SUB_09_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_09_ses-02_stroop/SUB_09_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_09_ses-02_stroop/SUB_09_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_10_ses-01_stroop/SUB_10_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_10_ses-01_stroop/SUB_10_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_10_ses-02_stroop/SUB_10_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_10_ses-02_stroop/SUB_10_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_11_ses-01_stroop/SUB_11_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_11_ses-01_stroop/SUB_11_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_11_ses-02_stroop/SUB_11_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_11_ses-02_stroop/SUB_11_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_12_ses-01_stroop/SUB_12_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_12_ses-01_stroop/SUB_12_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_12_ses-02_stroop/SUB_12_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_12_ses-02_stroop/SUB_12_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_13_ses-01_stroop/SUB_13_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_13_ses-01_stroop/SUB_13_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_13_ses-02_stroop/SUB_13_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_13_ses-02_stroop/SUB_13_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_14_ses-01_stroop/SUB_14_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_14_ses-01_stroop/SUB_14_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_14_ses-02_stroop/SUB_14_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_14_ses-02_stroop/SUB_14_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_15_ses-01_stroop/SUB_15_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_15_ses-01_stroop/SUB_15_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_15_ses-02_stroop/SUB_15_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_15_ses-02_stroop/SUB_15_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_16_ses-01_stroop/SUB_16_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_16_ses-01_stroop/SUB_16_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_16_ses-02_stroop/SUB_16_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_16_ses-02_stroop/SUB_16_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_17_ses-01_stroop/SUB_17_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_17_ses-01_stroop/SUB_17_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_17_ses-02_stroop/SUB_17_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_17_ses-02_stroop/SUB_17_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_18_ses-01_stroop/SUB_18_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_18_ses-01_stroop/SUB_18_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_18_ses-02_stroop/SUB_18_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_18_ses-02_stroop/SUB_18_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_19_ses-01_stroop/SUB_19_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_19_ses-01_stroop/SUB_19_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_19_ses-02_stroop/SUB_19_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_19_ses-02_stroop/SUB_19_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_20_ses-01_stroop/SUB_20_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_20_ses-01_stroop/SUB_20_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_20_ses-02_stroop/SUB_20_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_20_ses-02_stroop/SUB_20_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_21_ses-01_stroop/SUB_21_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_21_ses-01_stroop/SUB_21_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_21_ses-02_stroop/SUB_21_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_21_ses-02_stroop/SUB_21_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_22_ses-01_stroop/SUB_22_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_22_ses-01_stroop/SUB_22_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_22_ses-02_stroop/SUB_22_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_22_ses-02_stroop/SUB_22_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_23_ses-01_stroop/SUB_23_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_23_ses-01_stroop/SUB_23_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_23_ses-02_stroop/SUB_23_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_23_ses-02_stroop/SUB_23_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_24_ses-01_stroop/SUB_24_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_24_ses-01_stroop/SUB_24_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_24_ses-02_stroop/SUB_24_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_24_ses-02_stroop/SUB_24_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_25_ses-01_stroop/SUB_25_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_25_ses-01_stroop/SUB_25_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_25_ses-02_stroop/SUB_25_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_25_ses-02_stroop/SUB_25_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_26_ses-01_stroop/SUB_26_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_26_ses-01_stroop/SUB_26_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_26_ses-02_stroop/SUB_26_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_26_ses-02_stroop/SUB_26_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_27_ses-01_stroop/SUB_27_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_27_ses-01_stroop/SUB_27_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_27_ses-02_stroop/SUB_27_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_27_ses-02_stroop/SUB_27_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_28_ses-01_stroop/SUB_28_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_28_ses-01_stroop/SUB_28_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_28_ses-02_stroop/SUB_28_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_28_ses-02_stroop/SUB_28_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_29_ses-01_stroop/SUB_29_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_29_ses-01_stroop/SUB_29_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_29_ses-02_stroop/SUB_29_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_29_ses-02_stroop/SUB_29_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_30_ses-01_stroop/SUB_30_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_30_ses-01_stroop/SUB_30_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_30_ses-02_stroop/SUB_30_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_30_ses-02_stroop/SUB_30_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_31_ses-01_stroop/SUB_31_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_31_ses-01_stroop/SUB_31_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_31_ses-02_stroop/SUB_31_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_31_ses-02_stroop/SUB_31_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_32_ses-01_stroop/SUB_32_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_32_ses-01_stroop/SUB_32_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_32_ses-02_stroop/SUB_32_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_32_ses-02_stroop/SUB_32_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_33_ses-01_stroop/SUB_33_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_33_ses-01_stroop/SUB_33_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_33_ses-02_stroop/SUB_33_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_33_ses-02_stroop/SUB_33_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_34_ses-01_stroop/SUB_34_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_34_ses-01_stroop/SUB_34_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_34_ses-02_stroop/SUB_34_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_34_ses-02_stroop/SUB_34_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_35_ses-01_stroop/SUB_35_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_35_ses-01_stroop/SUB_35_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_35_ses-02_stroop/SUB_35_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_35_ses-02_stroop/SUB_35_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_36_ses-01_stroop/SUB_36_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_36_ses-01_stroop/SUB_36_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_36_ses-02_stroop/SUB_36_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_36_ses-02_stroop/SUB_36_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_37_ses-01_stroop/SUB_37_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_37_ses-01_stroop/SUB_37_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_37_ses-02_stroop/SUB_37_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_37_ses-02_stroop/SUB_37_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_38_ses-01_stroop/SUB_38_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_38_ses-01_stroop/SUB_38_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_38_ses-02_stroop/SUB_38_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_38_ses-02_stroop/SUB_38_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_39_ses-01_stroop/SUB_39_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_39_ses-01_stroop/SUB_39_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_39_ses-02_stroop/SUB_39_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_39_ses-02_stroop/SUB_39_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_40_ses-01_stroop/SUB_40_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_40_ses-01_stroop/SUB_40_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_40_ses-02_stroop/SUB_40_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_40_ses-02_stroop/SUB_40_ses-02_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_41_ses-01_stroop/SUB_41_ses-01_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_41_ses-01_stroop/SUB_41_ses-01_stroop_incong.nii \
/projects/Saidi/rawdata/Results/SUB_41_ses-02_stroop/SUB_41_ses-02_stroop_cong.nii \
/projects/Saidi/rawdata/Results/SUB_41_ses-02_stroop/SUB_41_ses-02_stroop_incong.nii
> cond_ME_roistats.txt
